#!/bin/bash

# install extension
jupyter labextension update jupyter-offlinenotebook --no-build
jupyter labextension install --minimize=False jupyterlab-code-snippets

# remove unnecessary directories when using the binder
rm -rf src
rm -rf style
rm -rf .github
rm -rf binder
rm -rf Design
rm -rf docs
rm package.json
rm tsconfig.json
rm yarn.lock
rm MANIFEST.in

jupyter lab clean
